### ISSUE TITLE
with open(filename, "r") as file: FileNotFoundError: [Errno 2] No such file or directory: 'working.txt'

### ISSUE THREAD

**Issue by SwiftExplorer567** [ccaner37/twitch-view-bot#1]
I cannot fix this problem. (I installed requirements). 

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\surme\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\surme\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\surme\Desktop\twitch-view-bot-main\twitch-view-bot-main\python\proxies\simple.py", line 9, in start_simple_thread
    get_new = _init_proxies(FILENAME)
  File "C:\Users\surme\Desktop\twitch-view-bot-main\twitch-view-bot-main\python\proxies\simple.py", line 28, in _init_proxies
    with open(filename, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'working.txt'`

**Comment by ccnrussell** [comment]
I updated python folder, please download it again. Put your ip addresses into the "working.txt" file. Thanks for reporting the issue. Have a nice day.

**Comment by SwiftExplorer567** [comment]
Thanks Caner.
